sudo: false

language: scala

scala:
  - 2.11.6
  - 2.10.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk: oraclejdk8

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
